### PR TITLE
Ignore "exclude-from-classmap" entries

### PR DESCRIPTION
**Pull request by alessandromorelli**
"exclude-from-classmap" autoload key is used to exclude _dev_ classes that live in a namespace contained in one the _prod_ namespaces.

Considering that _dev_ stuff of required packages is not useful or available to the root package, I think that we can safely ignore the "exclude-from-classmap" entries, neatly solving the problem with Symfony packages that do not contain the "Tests" directory.

### CODE REVIEW

**Comment by TangRufus** [comment]
Looks great 🎉


---


Do you have a project that requires `exclude-from-classmap` to be excluded?
So, that I could test on it.

---

Side note: Dev stuff should go into [`autoload-dev`](https://getcomposer.org/doc/04-schema.md#autoload-dev)but it still make sense for imposter to exclude `exclude-from-classmap`

**Comment by alessandromorelli** [comment]
Symfony has this use case where they have a Tests directory in the main repo, but when they extract a component and package it separately, they omit that directory.

There is surely a compelling reason for them to organize it like that, but anyway the result is that their packages make imposter barf.

I think that we can safely ignore `exclude-from-classmap` in any case.

Here's a test composer.json that show the problem: https://gist.github.com/alessandromorelli/85d672c16b7b4bc190178aab796eb0cd

**Comment by alessandromorelli** [comment]
We need to do that in a different code path, though.

Reviewing the code after your comment, I changed my mind a bit.

If we want to support `exclude-from-classmap` properly, I think that we have to:
- avoid generating candidate paths from entries in `exclude-from-classmap`
- parse the entries to generate a filter  on the file list obtained by enumerating the candidate paths

This PR adresses only the former, while the latter will be addressed in another PR.

Also, the directory scan should not fail on non existent paths, as some paths might be generated late in the setup.
I prepared a couple of PRs to address this specific issue.

**Comment by TangRufus** [comment]
Awesome!

Merged in https://github.com/TypistTech/imposter/pull/153 with tests.

**Pull request closed without merging**
